# Automated File Organizer Rules - 2025
settings:
  source_dir: "./Downloads_Mock"
  create_folders: true

categories:
  Documents:
    - .pdf
    - .docx
    - .txt
    - .pptx
    - .xlsx
    - .csv
    - .md
    - .epub
  Images:
    - .jpg
    - .jpeg
    - .png
    - .svg
    - .gif
    - .webp
    - .tiff
    - .bmp
    - .heic
  Media:
    - .mp3
    - .mp4
    - .mov
    - .mkv
    - .avi
    - .flv
    - .wav
  Archives:
    - .zip
    - .tar
    - .gz
    - .rar
    - .7z
    - .iso
